# permissions for end users to edit acmenamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: acmenamespace-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operatorize-my-stuff
    app.kubernetes.io/part-of: operatorize-my-stuff
    app.kubernetes.io/managed-by: kustomize
  name: acmenamespace-editor-role
rules:
- apiGroups:
  - tenants.mytenant.com
  resources:
  - acmenamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenants.mytenant.com
  resources:
  - acmenamespaces/status
  verbs:
  - get
